#!/bin/bash
# A script to build a custom .deb package by post-processing the one generated by Gradle.
# From https://gist.github.com/onlymash/596be855370559afeebbb354b8a0d197
set -e

# --- Configuration ---
APP_NAME="SubSched"
DEB_ARCH="${1:-amd64}" # default amd64
TOML_FILE="gradle/libs.versions.toml"
CUSTOM_RESOURCES_DIR="composeApp/packaging/linux"
#ICON_NAME="${APP_NAME}.png"
ICON_NAME="subsched_logo.png"
ICON_INSTALL_DIR="/usr/share/icons/hicolor/512x512/apps"
ORIGINAL_DEB_DIR="composeApp/build/compose/binaries/main-release/deb"
FINAL_DEB_DIR="composeApp/build/dist"

# --- Script Start ---

# 1. Read version from libs.versions.toml
echo "### 1. Reading version from '$TOML_FILE'..."
if [ ! -f "$TOML_FILE" ]; then
    echo "ERROR: Version catalog file not found at '$TOML_FILE'"
    exit 1
fi
VERSION=$(grep 'app-version' "$TOML_FILE" | cut -d '"' -f 2)
if [ -z "$VERSION" ]; then
    echo "ERROR: Could not find 'app-version' in '$TOML_FILE'"
    exit 1
fi
echo "  - Found app-version: $VERSION"


# 2. Build the basic .deb package with Gradle
echo "### 2. Building the basic DEB package with Gradle..."
./gradlew packageReleaseDeb


# 3. Find the original .deb file
ORIGINAL_DEB_PATH=$(find "$ORIGINAL_DEB_DIR" -name "*.deb")
if [ -z "$ORIGINAL_DEB_PATH" ]; then
    echo "ERROR: Original .deb file not found."
    exit 1
fi
echo "  - Found original DEB at: $ORIGINAL_DEB_PATH"


# 4. Unpack the original .deb file
WORK_DIR="composeApp/build/deb_work"
echo "### 3. Unpacking the original DEB file into '$WORK_DIR'..."
rm -rf "$WORK_DIR"
mkdir -p "$WORK_DIR"
dpkg-deb -R "$ORIGINAL_DEB_PATH" "$WORK_DIR"


# 5. Inject custom files
echo "### 4. Injecting custom files..."

# a. Inject .desktop file and replace placeholder
DESKTOP_TEMPLATE="$CUSTOM_RESOURCES_DIR/$APP_NAME.desktop"
DESTINATION_DESKTOP_DIR="$WORK_DIR/usr/share/applications"
mkdir -p "$DESTINATION_DESKTOP_DIR"
sed "s/@version@/$VERSION/g" "$DESKTOP_TEMPLATE" > "$DESTINATION_DESKTOP_DIR/$APP_NAME.desktop"
echo "  - Injected .desktop file with version '$VERSION'"

# b. Inject icon file
ICON_SOURCE_PATH="$CUSTOM_RESOURCES_DIR/$ICON_NAME"
DESTINATION_ICON_DIR="$WORK_DIR/$ICON_INSTALL_DIR"
if [ ! -f "$ICON_SOURCE_PATH" ]; then
    echo "WARNING: Icon file not found at '$ICON_SOURCE_PATH'. Skipping icon copy."
else
    mkdir -p "$DESTINATION_ICON_DIR"
    cp "$ICON_SOURCE_PATH" "$DESTINATION_ICON_DIR/"
    echo "  - Injected icon file to $ICON_INSTALL_DIR"
fi


# 6. Repack into the final .deb file with corrected ownership
FINAL_DEB_NAME="${APP_NAME}_${VERSION}_${DEB_ARCH}_custom.deb"
FINAL_DEB_PATH="$FINAL_DEB_DIR/$FINAL_DEB_NAME"
mkdir -p "$FINAL_DEB_DIR"
echo "### 5. Repacking into final DEB package..."

# The final, correct command to build a warning-free package
# Option first, then Command, then Arguments.
dpkg-deb --root-owner-group -b "$WORK_DIR" "$FINAL_DEB_PATH"


echo ""
echo "================================================="
echo "SUCCESS! Custom DEB package created at:"
echo "$FINAL_DEB_PATH"
echo "================================================="
