#!/bin/bash
# From https://gist.github.com/onlymash/596be855370559afeebbb354b8a0d197
# A script to automatically find a .deb package and convert it to an Arch Linux
# package by dynamically generating a PKGBUILD and using makepkg.
set -e

# --- Configuration ---
APP_NAME="SubSched"
DEB_SEARCH_DIR="composeApp/build/dist"
ARCH_BUILD_DIR="composeApp/build/arch_build"
FINAL_PKG_DIR="composeApp/build/dist"

# --- Main Logic ---

# First, check if the directory we need to search even exists.
if [ ! -d "$DEB_SEARCH_DIR" ]; then
    echo "ERROR: Directory '$DEB_SEARCH_DIR' not found."
    echo "Please run the './build-custom-deb.sh' script first to generate the .deb package."
    exit 1
fi

# 1. Automatically find the latest custom .deb file
echo "### 1. Searching for the latest .deb package in '$DEB_SEARCH_DIR'..."
# This command finds all .deb files (not custom ones anymore, to be more general)
DEB_FILE=$(find "$DEB_SEARCH_DIR" -name "*.deb" -print0 | xargs -0 ls -t | head -n 1)

if [ -z "$DEB_FILE" ]; then
    echo "ERROR: No .deb file found in '$DEB_SEARCH_DIR'."
    echo "Please run the './build-custom-deb.sh' script first."
    exit 1
fi
echo "  - Found package: $DEB_FILE"

# Convert the relative path to an absolute path
DEB_FILE_ABSOLUTE=$(readlink -f "$DEB_FILE")


# 2. Set up a clean build directory and extract the .deb archive
echo "### 2. Preparing Arch Linux build directory..."
rm -rf "$ARCH_BUILD_DIR"
mkdir -p "$ARCH_BUILD_DIR"
DEB_FILENAME=$(basename "$DEB_FILE")
(
    cd "$ARCH_BUILD_DIR"
    cp "$DEB_FILE_ABSOLUTE" "$DEB_FILENAME"
    ar x "$DEB_FILENAME"
)


# 3. Extract metadata from the control file
echo "### 3. Extracting metadata from .deb package..."
CONTROL_INFO=$(tar -xOf "$ARCH_BUILD_DIR/control.tar."* ./control)

# Read info and assign to variables
PKG_NAME=$(echo "$CONTROL_INFO" | grep -i '^Package:' | cut -d' ' -f2)
PKG_VER=$(echo "$CONTROL_INFO" | grep -i '^Version:' | cut -d' ' -f2 | cut -d'-' -f1)
PKG_DESC=$(echo "$CONTROL_INFO" | grep -i '^Description:' | cut -d' ' -f2-)
PKG_ARCH=$(echo "$CONTROL_INFO" | grep -i '^Architecture:' | cut -d' ' -f2)
if [ "$PKG_ARCH" = "amd64" ]; then
    PKG_ARCH="x86_64"
fi
PACKAGER=$(echo "$CONTROL_INFO" | grep -i '^Maintainer:' | cut -d' ' -f2-)
echo "  - Name: $PKG_NAME, Version: $PKG_VER, Arch: $PKG_ARCH"


# 4. Dynamically generate the PKGBUILD file
echo "### 4. Generating PKGBUILD file..."
cat <<EOF > "$ARCH_BUILD_DIR/PKGBUILD"
# Maintainer: $PACKAGER
# This PKGBUILD was automatically generated by a script.

pkgname='$APP_NAME'
pkgver='$PKG_VER'
pkgrel=1
pkgdesc='$PKG_DESC'
arch=('$PKG_ARCH')
url=''
license=('unknown')
depends=('java-runtime>=21')
source=("$DEB_FILENAME")
sha256sums=('SKIP')

package() {
  ar x "\$srcdir/$DEB_FILENAME"
  tar -xf data.tar.* -C "\$pkgdir/"
  
  # Create symlink for console command
  mkdir -p "\$pkgdir/usr/bin"
  ln -s "/opt/subsched/bin/SubSched" "\$pkgdir/usr/bin/subsched"
  echo 'ln -s "/opt/subsched/bin/SubSched" "\$pkgdir/usr/bin/subsched"'
}
EOF
echo "  - PKGBUILD created in '$ARCH_BUILD_DIR'"


# 5. Build the Arch Linux package using makepkg
echo "### 5. Building the Arch package with makepkg..."
(
    cd "$ARCH_BUILD_DIR"

    echo "  - Generating checksums using 'makepkg -g'..."
    CHECKSUM_LINE=$(makepkg -g)
    sed -i "s|sha2s56sums=('SKIP')|$CHECKSUM_LINE|" PKGBUILD
    echo "  - PKGBUILD updated with new checksums."

    PKGEXT='.pkg.tar.zst' makepkg -f --noconfirm
)


# 6. Move the final package and clean up
FINAL_PKG_FILE=$(find "$ARCH_BUILD_DIR" -name "*.pkg.tar*")
if [ -z "$FINAL_PKG_FILE" ]; then
    echo "ERROR: makepkg did not produce a package file."
    exit 1
fi
mkdir -p "$FINAL_PKG_DIR"
mv "$FINAL_PKG_FILE" "$FINAL_PKG_DIR/"

echo ""
echo "================================================="
echo "SUCCESS! Arch Linux package created at:"
echo "$FINAL_PKG_DIR/$(basename "$FINAL_PKG_FILE")"
echo "================================================="